
SELECT * FROM Projects
ORDER BY ID, PID ASC
LIMIT 6;
SELECT 
    R1.ID, R1.PID, R1.SID, R2.SN, R3.PN, R4.MID, R5.MN
FROM
    Projects_ID_PID_SID R1
    INNER JOIN Projects_SID_SN R2 ON R2.SID = R1.SID
    INNER JOIN Projects_PID_PN R3 ON R3.PID = R1.PID
    INNER JOIN Projects_ID_MID R4 ON R4.ID = R1.ID
    INNER JOIN Projects_MID_MN R5 ON R5.MID = R4.MID
ORDER BY R1.ID, R1.PID ASC
LIMIT 6;




